.nh
.TH postmark 1 "May 2005" postmark "User Manual"
.SH NAME
\fBpostmark\fP \- a file system benchmark based around small file operations

.SH SYNOPSIS
\fBpostmark\fP [config-file]

.SH DESCRIPTION
\fBpostmark\fP is a benchmark that's based around small file operations similar to those used on large mail servers and news servers.

.PP
When \fBpostmark\fP is run it gives a command-line interface to configure and run tests. The "help" command displays basic information on how to operate it.

.PP
The name of a text file containing commands may be specified on the command line.

.SH COMMANDS
The following \fBpostmark\fP commands are available interactively.
.TP
\fBload\fP \fIFILE\fP
Read configuration file from \fIFILE\fP\&.

.TP
\fBrun\fP
Runs one iteration of benchmark

.TP
\fBshow\fP
Displays current configuration

.TP
\fBhelp\fP
Prints out available commands

.TP
\fBquit\fP
Exit program

.SH CONFIGURATION
The following \fBpostmark\fP configuration settings are available, either interactively or by the specified config file:
.TP
\fBset\fP \fBsize\fP \fIMIN\fP \fIMAX\fP
Sets low and high bounds of files in bytes.

Defaults to \fB500 10000\fR\&.

.TP
\fBset number\fP \fINUM\fP
Sets number of simultaneous files.

Defaults to \fB500\fR\&.

.TP
\fBset seed\fP \fINUM\fP
Sets seed for random number generator.

Defaults to \fB42\fR\&.

.TP
\fBset transactions\fP \fINUM\fP
Sets number of transactions.

Defaults to \fB500\fR\&.

.TP
\fBset location\fP \fIDIR\fP
Sets location of working files.

Defaults to the present working directory.

.TP
\fBset subdirectories\fP \fINUM\fP
Sets number of subdirectories.

The default is to use a single working directory.

.TP
\fBset read\fP \fIBYTES\fP
Sets read block size in bytes.

The default is \fB512\fR\&.

.TP
\fBset write\fP \fIBYTES\fP
Sets write block size in bytes.

The default is \fB512\fR\&.

.TP
\fBset buffering\fP [true|false]
Sets usage of buffered I/O.

The default is \fBtrue\fR\&.

.TP
\fBset bias read\fP \fINUM\fP
Sets the chance of choosing read over append.

The default is \fB5\fR\&.

.TP
\fBset bias create\fP \fINUM\fP
Sets the chance of choosing create over delete.

The default is \fB5\fR\&.

.TP
\fBset report\fP [verbose|terse]
Choose verbose or terse report format.

The default is \fBverbose\fR\&.

.SH AUTHORS
Written by Jeffrey Katcher (katcher@netapp.com) under contract to Network Appliance.

.PP
The manual page was written by Russell Coker (russell@coker.com.au),
for the Debian GNU/Linux system.
