.nh
.TH postmark 1 "May 2005" postmark "User Manual"

.SH NAME
\fBpostmark\fP \- a file system benchmark based around small file operations

.SH SYNOPSIS
\fBpostmark\fP [config-file]

.SH DESCRIPTION
\fBpostmark\fP is a benchmark that's based around small file operations similar to those used on large mail servers and news servers.

.PP
When \fBpostmark\fP is run it gives a command-line interface to configure and run tests. The "help" command displays basic information on how to operate it.

.PP
The name of a text file containing commands may be specified on the command line.

.SH COMMANDS
The following \fBpostmark\fP commands are available, either interactively or by the specified config file:
.TP
\fBset\fP \fBsize\fP
Sets low and high bounds of files

.TP
\fBset number\fP
Sets number of simultaneous files

.TP
\fBset seed\fP
Sets seed for random number generator

.TP
\fBset transactions\fP
Sets number of transactions

.TP
\fBset location\fP
Sets location of working files

.TP
\fBset subdirectories\fP
Sets number of subdirectories

.TP
\fBset read\fP
Sets read block size

.TP
\fBset write\fP
Sets write block size

.TP
\fBset buffering\fP
Sets usage of buffered I/O

.TP
\fBset bias read\fP
Sets the chance of choosing read over append

.TP
\fBset bias create\fP
Sets the chance of choosing create over delete

.TP
\fBset report\fP
Choose verbose or terse report format

.TP
\fBrun\fP
Runs one iteration of benchmark

.TP
\fBload\fP
Read configuration file

.TP
\fBshow\fP
Displays current configuration

.TP
\fBhelp\fP
Prints out available commands

.TP
\fBquit\fP
Exit program

.SH AUTHORS
Written by Jeffrey Katcher (katcher@netapp.com) under contract to Network Appliance.

.PP
The manual page was written by Russell Coker (russell@coker.com.au),
for the Debian GNU/Linux system.
